version: '3'
services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=weatherPost
      - POSTGRES_USER=postgres
      - POSTGRES_DB=weatherDB
    ports:
      - 5432:5432
    container_name: weatherDB_postgres
    volumes:
      - ./weatherDB/init-scripts:/docker-entrypoint-initdb.d

  access:
    build:
      context: ./weatherDB
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    container_name: weatherDB_access
    depends_on:
      - postgres

  app:
    build:
      context: ./weatherappspring
      dockerfile: Dockerfile
    ports:
      - 2345:2345
    container_name: weather-api-container
    image: weather-api-image

  weather-app:
    build:
      context: ./weatherfrontend
      dockerfile: Dockerfile
    ports:
      - 5173:5173
