services:
  idm:
    container_name: idm
    image: quay.io/keycloak/keycloak:19.0.3-legacy
    ports:
      - 0.0.0.0:8080:8080
    volumes:
      - .:/tmp/keycloak
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=passKeycloakAdmin
      - KEYCLOAK_IMPORT=/tmp/keycloak/java-starter-realm.json
  db-person:
    container_name: db-person
    image: postgres:15.2-alpine
    ports:
      - 0.0.0.0:5434:5432
    environment:
      - POSTGRES_USER=person
      - POSTGRES_PASSWORD=passGeheim
      - POSTGRES_DB=person
  db-auftrag:
    container_name: db-auftrag
    image: postgres:15.2-alpine
    ports:
      - 0.0.0.0:5433:5432
    environment:
      - POSTGRES_USER=auftrag
      - POSTGRES_PASSWORD=passGeheim
      - POSTGRES_DB=auftrag
